name: Tests
on:
  schedule:
    - cron: "0 0 1 */4 *"
  push:
    branches: 
      - "master"
      - "release/**"
  pull_request:
    branches: 
      - "master"
      - "dev"
env:
  CARGO_TERM_COLOR: always
  STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
  PROJECT_PATH: ${{ github.workspace }}
  RUST_BACKTRACE: 1
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: bash ./setup/actions/create_env_file.sh
    - name: Set up config for storefronts
      run: cargo run --release -- config -a --test_flag
    - name: Cache Steam games
      run: cargo run --release -- --update-cache --test_flag
    - name: Run tests
      run: cargo test --release -- --test-threads=1
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create env file
        run: .\setup\actions\create_env_file.ps1
      - name: Set up config for storefronts
        run: cargo run --release -- config -a --test_flag
      - name: Cache Steam games
        run: cargo run --release -- --update-cache --test_flag
      - name: Run tests
        run: cargo test --release -- --test-threads=1