name: Tests
permissions:
  contents: read
on:
  schedule:
    - cron: "0 0 1 */4 *"
  push:
    branches: 
      - "master"
      - "release/**"
  pull_request:
    branches: 
      - "master"
      - "dev"
env:
  CARGO_TERM_COLOR: always
  STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
  PROJECT_PATH: ${{ github.workspace }}
  RUST_BACKTRACE: 1
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: bash ./setup/actions/create_env_file.sh
    - name: Configure project
      run: |
        # Set properties
        cargo run --release -- config properties --from-env
        cargo run --release -- config properties --test_mode 1
        # Set store fronts
        cargo run --release -- config settings -a 
      shell: bash
    - name: Cache Steam games
      run: cargo run --release -- --update-cache
    - name: Run tests
      run: cargo test --release -- --test-threads=1 --show-output
  windows:
    needs: linux
    if: always()
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure toolchain
        run: |
          # Install toolchain
          rustup toolchain install stable-x86_64-pc-windows-gnu
          # Set default toolchain
          rustup default stable-x86_64-pc-windows-gnu
          # List toolchains
          echo "List Toolchains:"
          rustup toolchain list
        shell: pwsh
      - name: Create env file
        run: .\setup\actions\create_env_file.ps1
      - name: Configure project
        run: |
          # Set properties
          cargo run --release -- config properties --from-env
          cargo run --release -- config properties --test_mode 1
          # Set store fronts
          cargo run --release -- config settings -a 
        shell: pwsh
      - name: Cache Steam
        run: cargo run --release -- --update-cache
      - name: Run tests
        run: cargo test --release -- --test-threads=1 --show-output